[tool.poetry]
name = "vidvort-api"
version = "0.1.0"
description = ""
authors = ["theharshpat <harsh.patel.magic105@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
